using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AoC.SourceGenerator;

[Generator]
public class AoCDayRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    { 
        var dayClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AoC.Core.AoCDayAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ctx
            )
            .Collect();

        var compilationAndClasses = context.CompilationProvider.Combine(dayClasses);
        
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (_, classSymbols) = source;

            var entries = new List<(int year, int day, string fqName)>();

            foreach (var c in classSymbols)
            {
                if (c.TargetSymbol is not INamedTypeSymbol type ||
                    !type.AllInterfaces.Any(i => i.ToDisplayString() == "AoC.Core.IAoCDay"))
                {
                    continue;
                }
                
                var attr = type.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "AoC.Core.AoCDayAttribute");

                if (attr is null)
                {
                    continue;
                }
                
                var year = (int)attr.ConstructorArguments[0].Value!;
                var day = (int)attr.ConstructorArguments[1].Value!;
                
                entries.Add((year, day, type.ToDisplayString()));
            }

            var sourceText = GenerateRegistry(entries);
            spc.AddSource("AoCDayRegistry.g.cs", sourceText);
        });
    }

    private static string GenerateRegistry(IEnumerable<(int year, int day, string fqName)> entries)
    {
        var sb = new StringBuilder("""
                                   /// <auto-generated/>
                                   #nullable enable
                                   using System.Collections.Generic;
                                   using AoC.Core;

                                   namespace AoC.Tool;

                                   internal static class AoCRegistry
                                   {
                                       private static readonly Dictionary<(int year, int day), IAoCDay> _days = new()
                                       {

                                   """);
        foreach (var (year, day, fqName) in entries.OrderBy(e => e.year).ThenBy(e => e.day))
        {
            sb.AppendLine($"        [({year}, {day})] = new {fqName}(),");
        }

        sb.AppendLine("""
                          };

                          public static bool TryGet(int year, int day, out IAoCDay? dayInstance)
                          {
                              _days.TryGetValue((year, day), out dayInstance);
                              return dayInstance is not null;
                          }
                      }
                      """);

        return sb.ToString();
    }
}
