using System.Text;
using Microsoft.CodeAnalysis;

namespace AoC.SourceGenerator;

[Generator]
public class AoCMainRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;
        
        context.RegisterSourceOutput(compilationProvider, static (spc, compilation) =>
        {
            var yearRegistries = new List<(int year, string typeName)>();

            // Look for assembly attributes in referenced assemblies
            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
                {
                    foreach (var attr in assemblySymbol.GetAttributes())
                    {
                        if (attr.AttributeClass?.ToDisplayString() == "AoC.Core.AoCYearRegistryAttribute")
                        {
                            var year = (int)attr.ConstructorArguments[0].Value!;
                            var registryType = (INamedTypeSymbol)attr.ConstructorArguments[1].Value!;
                            var typeName = registryType.ToDisplayString();
                            
                            yearRegistries.Add((year, typeName));
                        }
                    }
                }
            }

            // Also check current compilation
            foreach (var attr in compilation.Assembly.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == "AoC.Core.AoCYearRegistryAttribute")
                {
                    var year = (int)attr.ConstructorArguments[0].Value!;
                    var registryType = (INamedTypeSymbol)attr.ConstructorArguments[1].Value!;
                    var typeName = registryType.ToDisplayString();
                    
                    yearRegistries.Add((year, typeName));
                }
            }

            // Always generate in tool project, even if no year registries exist yet
            if (compilation.AssemblyName == "AoC.Tool")
            {
                var combinedSource = GenerateCombinedRegistries(yearRegistries);
                spc.AddSource("AoCRegistries.g.cs", combinedSource);
            }
        });
    }

    private static string GenerateCombinedRegistries(List<(int year, string typeName)> yearRegistries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using AoC.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace AoC.Tool;");
        sb.AppendLine();
        
        // Generate main registry
        sb.AppendLine("internal static class AoCMainRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<int, IAoCYearRegistry> _yearRegistries = new()");
        sb.AppendLine("    {");
        
        foreach (var (year, typeName) in yearRegistries.OrderBy(r => r.year))
        {
            sb.AppendLine($"        [{year}] = new {typeName}(),");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryGetYear(int year, out IAoCYearRegistry? yearRegistry)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _yearRegistries.TryGetValue(year, out yearRegistry);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryGetDay(int year, int day, out IAoCDay? dayInstance)");
        sb.AppendLine("    {");
        sb.AppendLine("        dayInstance = null;");
        sb.AppendLine("        return TryGetYear(year, out var yearRegistry) && ");
        sb.AppendLine("               yearRegistry != null && yearRegistry.TryGetDay(day, out dayInstance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static IEnumerable<int> GetAvailableYears() => _yearRegistries.Keys;");
        sb.AppendLine();
        sb.AppendLine("    public static IEnumerable<int> GetAvailableDays(int year)");
        sb.AppendLine("    {");
        sb.AppendLine("        return TryGetYear(year, out var yearRegistry) && yearRegistry != null");
        sb.AppendLine("            ? yearRegistry.Days.Keys ");
        sb.AppendLine("            : Enumerable.Empty<int>();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

