using System.Text;
using Microsoft.CodeAnalysis;

namespace AoC.SourceGenerator;

[Generator]
public class AoCRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        AddYearAttribute(context);
        AddDayAttribute(context);
        AddDayInterface(context);
        AddYearRegistryInterface(context);
    }

    private static void AddYearAttribute(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("AoCYearRegistryAttribute.g.cs",
            """
            // <auto-generated/>
            using System;

            namespace AoC.SourceGenerator;

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            public sealed class AoCYearRegistryAttribute(int year, Type registryType) : Attribute
            {
                public int Year { get; } = year;
                public Type RegistryType { get; } = registryType;
            }
            """
        ));
    }

    private static void AddDayAttribute(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("AoCDayAttribute.g.cs",
            """
            // <auto-generated/>
            using System;

            namespace AoC.SourceGenerator;

            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
            public sealed class AoCDayAttribute(int year, int day) : Attribute
            {
                public int Year { get; } = year;
                public int Day { get; } = day;
            }
            """
        ));
    }

    private static void AddDayInterface(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("IAoCDay.g.cs",
            """
            // <auto-generated/>
            namespace AoC.SourceGenerator;

            public interface IAoCDay
            {
                string Part1(string input);
                string Part2(string input);
            }
            """
        ));
    }

    private static void AddYearRegistryInterface(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("IAoCYearRegistry.g.cs",
            """
            // <auto-generated/>
            using System.Collections.Generic;

            namespace AoC.SourceGenerator;

            public interface IAoCYearRegistry
            {
                int Year { get; }
                IReadOnlyDictionary<int, IAoCDay> Days { get; }
                bool TryGetDay(int day, out IAoCDay? dayInstance);
            }
            """
        ));
    }

    private static string GenerateCombinedRegistries(List<(int year, string typeName)> yearRegistries, string assemblyName)
    {
        var namespaceName = assemblyName.Replace(".", "");
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("// Generated types are in the same namespace");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        
        // Generate main registry
        sb.AppendLine("internal static class AoCRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<int, IAoCYearRegistry> _yearRegistries = new()");
        sb.AppendLine("    {");
        
        foreach (var (year, typeName) in yearRegistries.OrderBy(r => r.year))
        {
            sb.AppendLine($"        [{year}] = new {typeName}(),");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryGetYear(int year, out IAoCYearRegistry? yearRegistry)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _yearRegistries.TryGetValue(year, out yearRegistry);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryGetDay(int year, int day, out IAoCDay? dayInstance)");
        sb.AppendLine("    {");
        sb.AppendLine("        dayInstance = null;");
        sb.AppendLine("        return TryGetYear(year, out var yearRegistry) && ");
        sb.AppendLine("               yearRegistry != null && yearRegistry.TryGetDay(day, out dayInstance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static IEnumerable<int> GetAvailableYears() => _yearRegistries.Keys;");
        sb.AppendLine();
        sb.AppendLine("    public static IEnumerable<int> GetAvailableDays(int year)");
        sb.AppendLine("    {");
        sb.AppendLine("        return TryGetYear(year, out var yearRegistry) && yearRegistry != null");
        sb.AppendLine("            ? yearRegistry.Days.Keys ");
        sb.AppendLine("            : Enumerable.Empty<int>();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

